export type PlayerTier = "elite" | "premium" | "mid" | "emerging"

export interface Player {
  id: string
  rank: number
  name: string
  nationality: string
  club: string
  position: string
  age: number
  marketValue: number
  tier: PlayerTier
  overallScore: number
  commercialScore: number
  performanceScore: number
  socialScore: number
  rankChange: number
  trendData: number[]
  trend: "up" | "down" | "flat"
}

export const mockPlayers: Player[] = [
  {
    id: "1",
    rank: 1,
    name: "Kylian Mbappé",
    nationality: "France",
    club: "Real Madrid",
    position: "FW",
    age: 27,
    marketValue: 180,
    tier: "elite",
    overallScore: 98,
    commercialScore: 97,
    performanceScore: 96,
    socialScore: 99,
    rankChange: 0,
    trendData: [92, 94, 93, 96, 97, 98],
    trend: "up",
  },
  {
    id: "2",
    rank: 2,
    name: "Erling Haaland",
    nationality: "Norway",
    club: "Manchester City",
    position: "FW",
    age: 25,
    marketValue: 175,
    tier: "elite",
    overallScore: 96,
    commercialScore: 94,
    performanceScore: 99,
    socialScore: 92,
    rankChange: 2,
    trendData: [88, 90, 92, 94, 95, 96],
    trend: "up",
  },
  {
    id: "3",
    rank: 3,
    name: "Jude Bellingham",
    nationality: "England",
    club: "Real Madrid",
    position: "MF",
    age: 22,
    marketValue: 150,
    tier: "elite",
    overallScore: 94,
    commercialScore: 96,
    performanceScore: 92,
    socialScore: 95,
    rankChange: 1,
    trendData: [78, 82, 86, 90, 92, 94],
    trend: "up",
  },
  {
    id: "4",
    rank: 4,
    name: "Vinícius Jr",
    nationality: "Brazil",
    club: "Real Madrid",
    position: "FW",
    age: 25,
    marketValue: 150,
    tier: "elite",
    overallScore: 93,
    commercialScore: 95,
    performanceScore: 91,
    socialScore: 94,
    rankChange: -2,
    trendData: [90, 92, 93, 94, 93, 93],
    trend: "flat",
  },
  {
    id: "5",
    rank: 5,
    name: "Florian Wirtz",
    nationality: "Germany",
    club: "Bayer Leverkusen",
    position: "MF",
    age: 22,
    marketValue: 130,
    tier: "elite",
    overallScore: 91,
    commercialScore: 88,
    performanceScore: 94,
    socialScore: 86,
    rankChange: 3,
    trendData: [70, 75, 80, 85, 88, 91],
    trend: "up",
  },
  {
    id: "6",
    rank: 6,
    name: "Pedri",
    nationality: "Spain",
    club: "Barcelona",
    position: "MF",
    age: 23,
    marketValue: 120,
    tier: "premium",
    overallScore: 89,
    commercialScore: 86,
    performanceScore: 92,
    socialScore: 88,
    rankChange: 0,
    trendData: [84, 85, 86, 88, 88, 89],
    trend: "flat",
  },
  {
    id: "7",
    rank: 7,
    name: "Jamal Musiala",
    nationality: "Germany",
    club: "Bayern Munich",
    position: "MF",
    age: 23,
    marketValue: 130,
    tier: "premium",
    overallScore: 88,
    commercialScore: 85,
    performanceScore: 90,
    socialScore: 87,
    rankChange: 1,
    trendData: [78, 80, 83, 85, 87, 88],
    trend: "up",
  },
  {
    id: "8",
    rank: 8,
    name: "Bukayo Saka",
    nationality: "England",
    club: "Arsenal",
    position: "FW",
    age: 24,
    marketValue: 120,
    tier: "premium",
    overallScore: 87,
    commercialScore: 89,
    performanceScore: 86,
    socialScore: 88,
    rankChange: -1,
    trendData: [82, 84, 85, 86, 87, 87],
    trend: "flat",
  },
  {
    id: "9",
    rank: 9,
    name: "Lamine Yamal",
    nationality: "Spain",
    club: "Barcelona",
    position: "FW",
    age: 18,
    marketValue: 150,
    tier: "emerging",
    overallScore: 86,
    commercialScore: 92,
    performanceScore: 82,
    socialScore: 94,
    rankChange: 5,
    trendData: [60, 68, 74, 80, 84, 86],
    trend: "up",
  },
  {
    id: "10",
    rank: 10,
    name: "Cole Palmer",
    nationality: "England",
    club: "Chelsea",
    position: "MF",
    age: 23,
    marketValue: 100,
    tier: "premium",
    overallScore: 85,
    commercialScore: 84,
    performanceScore: 88,
    socialScore: 82,
    rankChange: 2,
    trendData: [72, 76, 79, 82, 84, 85],
    trend: "up",
  },
  {
    id: "11",
    rank: 11,
    name: "Phil Foden",
    nationality: "England",
    club: "Manchester City",
    position: "MF",
    age: 25,
    marketValue: 110,
    tier: "premium",
    overallScore: 84,
    commercialScore: 82,
    performanceScore: 87,
    socialScore: 80,
    rankChange: -3,
    trendData: [86, 85, 85, 84, 84, 84],
    trend: "down",
  },
  {
    id: "12",
    rank: 12,
    name: "Rodri",
    nationality: "Spain",
    club: "Manchester City",
    position: "MF",
    age: 29,
    marketValue: 100,
    tier: "premium",
    overallScore: 83,
    commercialScore: 75,
    performanceScore: 95,
    socialScore: 70,
    rankChange: 0,
    trendData: [80, 81, 82, 82, 83, 83],
    trend: "flat",
  },
]

export interface StatCard {
  label: string
  value: string | number
  change: number
  trend: "up" | "down" | "flat"
}

export const mockStats: StatCard[] = [
  { label: "Total Players Tracked", value: "2,847", change: 12, trend: "up" },
  { label: "Elite Tier", value: 156, change: 3, trend: "up" },
  { label: "Avg Market Value", value: "€47.2M", change: -2, trend: "down" },
  { label: "Active Transfers", value: 23, change: 5, trend: "up" },
]
